version: "3.8"
services:
  otus:
    build: .
    image: otus17
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=$jdbc:postgresql://postgres:5432/mydatabase
      - DB_NAME=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=secret
  postgres:
    image: 'postgres:13.7-alpine'
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=myuser
    ports:
      - '6541:5432'
