version: "3.8"
services:
  otus:
    build: .
    image: otus17
    ports:
      - "80:8000"
    #depends_on:
     # - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:mydatabase
 #     - SPRING_DATASOURCE_USERNAME=root
 #     - SPRING_DATASOURCE_PASSWORD=password
  #postgres:
 #   image: 'postgres:13.7-alpine'
 #   environment:
 #     - POSTGRES_DB=mydatabase
 #     - POSTGRES_PASSWORD=secret
 #     - POSTGRES_USER=myuser
 #   ports:
 #     - '6541:5432'
