apiVersion: apps/v1
kind: Deployment
metadata:
  name: otus-dp
  labels:
    app: otus-dp
spec:
  replicas: 2
  selector:
    matchLabels:
      env: prod
  template:
    metadata:
      labels:
        env: prod
    spec:
      containers:
      - name: otus-app
        image: andrey1andrey/otus17:latest
        ports:
        - containerPort: 8000
        env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: otus-cm
              key: spring_datasource_url
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: otus-secret
              key: password